import type { ProductSpec } from '@pm-agent/domain'

function list(items: string[]): string {
  return items.map((item) => `- ${item}`).join('\n')
}

export function renderProductSpecMarkdown(spec: ProductSpec): string {
  const activeRequirements = spec.requirements.filter((requirement) => requirement.status !== 'removed')
  const requirementSections = activeRequirements.map((requirement) => {
    const screens = spec.screens.filter((screen) => screen.requirementIds.includes(requirement.id)).map((screen) => `${screen.id} · ${screen.title}`)
    const stories = spec.stories.filter((story) => story.requirementIds.includes(requirement.id)).map((story) => `${story.id} · ${story.title}`)
    return [
      `### ${requirement.id} · ${requirement.title}`,
      '',
      requirement.description,
      '',
      `- Priority: ${requirement.priority}`,
      `- Status: ${requirement.status}`,
      `- Screens: ${screens.join(', ') || 'Chưa có'}`,
      `- Stories: ${stories.join(', ') || 'Chưa có'}`,
      '',
      '**Acceptance criteria**',
      '',
      list(requirement.acceptanceCriteria),
    ].join('\n')
  }).join('\n\n')

  const traceability = activeRequirements.map((requirement) => {
    const screenIds = spec.screens.filter((screen) => screen.requirementIds.includes(requirement.id)).map((screen) => screen.id).join(', ')
    const storyIds = spec.stories.filter((story) => story.requirementIds.includes(requirement.id)).map((story) => story.id).join(', ')
    return `| ${requirement.id} | ${screenIds || '-'} | ${storyIds || '-'} |`
  }).join('\n')

  return [
    `# ${spec.title}`,
    '',
    `> ProductSpec v${spec.version} · ${spec.status} · generated by PM Lifecycle Agent`,
    '',
    '## Product brief',
    '',
    spec.idea.summary,
    '',
    `**Product type:** ${spec.idea.productType}`,
    '',
    '**Target users**',
    '',
    list(spec.idea.targetUsers),
    '',
    '## Goals',
    '',
    spec.goals.length > 0 ? spec.goals.map((goal) => `- **${goal.title}:** ${goal.metric}`).join('\n') : '- Chưa xác định',
    '',
    '## Scope',
    '',
    requirementSections,
    '',
    '## Screens',
    '',
    spec.screens.map((screen, index) => `${index + 1}. **${screen.title}** — ${screen.purpose}`).join('\n'),
    '',
    '## Decision record',
    '',
    spec.decisions.map((decision) => [
      `### ${decision.id} · ${decision.title}`,
      '',
      `- Question: ${decision.question}`,
      `- Choice: ${decision.choice}`,
      `- Rationale: ${decision.rationale}`,
      `- Status: ${decision.status}`,
    ].join('\n')).join('\n\n'),
    '',
    '## Dependencies',
    '',
    spec.dependencies.length > 0
      ? spec.dependencies.map((dependency) => `- **${dependency.title}** (${dependency.dependencyType}) — ${dependency.requirementIds.join(', ')}`).join('\n')
      : '- Không có dependency đã ghi nhận',
    '',
    '## Traceability',
    '',
    '| Requirement | Screens | Stories |',
    '| --- | --- | --- |',
    traceability,
    '',
    '## Artifact status',
    '',
    '- Figma: generated through guarded preflight, approval and read-back flow',
    '- Jira: local mock only; MCP connector will be added later',
    '- Document: this Markdown file is the current PRD artifact',
    '',
  ].join('\n')
}
